### ISSUE TITLE
使用Tasker调用时闪退

### ISSUE THREAD

**Issue by BlessWz** [HMBSbige/ShadowsocksR-Android#31] opened 2019-11-21 11:49 UTC
![Screenshot_20191121-180336_Tasker](https://user-images.githubusercontent.com/30049891/69335215-66a66f80-0c97-11ea-95b4-9612affdca27.png)
![Screenshot_20191121-180320_ShadowsocksR](https://user-images.githubusercontent.com/30049891/69335216-673f0600-0c97-11ea-980a-bd0afb988b35.png)
![Screenshot_20191121-180311_Tasker](https://user-images.githubusercontent.com/30049891/69335217-673f0600-0c97-11ea-9d86-50ac82f287cb.png)
11-21 19:35:12.485  7832  7832 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@d2eb566
11-21 19:35:12.539  7832  7832 D AndroidRuntime: Shutting down VM
11-21 19:35:12.540  7832  7832 E AndroidRuntime: FATAL EXCEPTION: main
11-21 19:35:12.540  7832  7832 E AndroidRuntime: Process: com.bige0.shadowsocksr, PID: 7832
11-21 19:35:12.540  7832  7832 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bige0.shadowsocksr/com.bige0.shadowsocksr.TaskerActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class androidx.appcompat.widget.RecyclerView
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2949)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6693)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class androidx.appcompat.widget.RecyclerView
11-21 19:35:12.540  7832  7832 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class androidx.appcompat.widget.RecyclerView
11-21 19:35:12.540  7832  7832 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/com.bige0.shadowsocksr-ZaiYeLOGXfFd-wwUyaElHQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.bige0.shadowsocksr-ZaiYeLOGXfFd-wwUyaElHQ==/lib/arm64, /data/app/com.bige0.shadowsocksr-ZaiYeLOGXfFd-wwUyaElHQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:606)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at com.bige0.shadowsocksr.TaskerActivity.onCreate(TaskerActivity.kt:24)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2929)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6693)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-21 19:35:12.540  7832  7832 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
11-21 19:35:16.545  7832  7832 W GAv4    : syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
11-21 19:35:16.573  7832  7832 I Process : Sending signal. PID: 7832 SIG: 9
11-21 19:35:21.139  9185  9185 E e0.shadowsocks: Not starting debugger since process cannot load the jdwp agent.
11-21 19:35:21.236  9185  9185 V Riru    : hook removed
11-21 19:35:21.236  9185  9185 V Riru    : location_report_enabler: forkAndSpecializePost
11-21 19:35:21.328  9185  9185 I GAv4    : Google Analytics 12.4.51 is starting up. To enable debug logging on a device run:
11-21 19:35:21.328  9185  9185 I GAv4    :   adb shell setprop log.tag.GAv4 DEBUG
11-21 19:35:21.328  9185  9185 I GAv4    :   adb logcat -s GAv4
11-21 19:35:21.342  9185  9202 W GAv4    : CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
11-21 19:35:21.414  9185  9185 W GoogleTagManager: Failed to extract the container from the resource file. Resource is a UTF-8 encoded string but doesn't contain a JSON container
11-21 19:35:21.992  9185  9185 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
11-21 19:35:22.116  9185  9185 D AndroidRuntime: Shutting down VM
11-21 19:35:22.117  9185  9185 E AndroidRuntime: FATAL EXCEPTION: main
11-21 19:35:22.117  9185  9185 E AndroidRuntime: Process: com.bige0.shadowsocksr, PID: 9185
11-21 19:35:22.117  9185  9185 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bige0.shadowsocksr/com.bige0.shadowsocksr.TaskerActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class androidx.appcompat.widget.RecyclerView
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2949)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6693)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class androidx.appcompat.widget.RecyclerView
11-21 19:35:22.117  9185  9185 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class androidx.appcompat.widget.RecyclerView
11-21 19:35:22.117  9185  9185 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/com.bige0.shadowsocksr-ZaiYeLOGXfFd-wwUyaElHQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.bige0.shadowsocksr-ZaiYeLOGXfFd-wwUyaElHQ==/lib/arm64, /data/app/com.bige0.shadowsocksr-ZaiYeLOGXfFd-wwUyaElHQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:606)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at com.bige0.shadowsocksr.TaskerActivity.onCreate(TaskerActivity.kt:24)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2929)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6693)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-21 19:35:22.117  9185  9185 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
11-21 19:35:22.190  9185  9195 I e0.shadowsocks: Background concurrent copying GC freed 168819(8MB) AllocSpace objects, 60(2MB) LOS objects, 67% free, 5MB/17MB, paused 821us total 125.244ms
11-21 19:35:22.530  9185  9210 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
11-21 19:35:26.122  9185  9185 W GAv4    : syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
11-21 19:35:27.150  9185  9202 E GAv4    : Successfully bound to service but never got onServiceConnected callback
11-21 19:35:31.501  9185  9208 W GoogleTagManager: IOException getting Ad Id Info
11-21 19:35:31.501  9185  9208 W GoogleTagManager: java.io.IOException: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:16)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:27)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:47)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.tagmanager.zzb.zzgv(Unknown Source:3)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.tagmanager.zza.zzgu(Unknown Source:53)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.tagmanager.zza.zzb(Unknown Source:72)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.tagmanager.zzc.run(Unknown Source:2)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at java.lang.Thread.run(Thread.java:764)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: Caused by: java.util.concurrent.TimeoutException: Timed out waiting for the service connection
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.common.BlockingServiceConnection.getServiceWithTimeout(Unknown Source:13)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:4)
11-21 19:35:31.501  9185  9208 W GoogleTagManager: 	... 7 more
11-21 19:35:41.485  9293  9293 E e0.shadowsocks: Not starting debugger since process cannot load the jdwp agent

**Comment by HMBSbige** [comment] 2019-11-21 12:17
Duplicate of #15

**Closed by HMBSbige** 2019-11-21 12:17 UTC
Labels: bug, duplicate
